# Notes- Implementation of ANN

Fully Connected Layers with Fully Cnnected layer.



In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
tf.__version__

'2.3.1'

# 1. Data Preprocessing

## Importing the dataset

In [2]:
dataset = pd.read_csv("Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data
**Label Encoding the "Gender" column**

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [6]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


**One Hot Encoding the "Geography" column**

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


 ### Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN
### Initializing the ANN

In [12]:
# Creating / Initializing the ANN Model
ann = tf.keras.models.Sequential()

# Adding the Input layer.
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
# The first hidden layes has 6 Neurons and it's selected by experimentation.

# adding the second Hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the Output Layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) 
# The Dependent variable is a binary varible hence we need onlt One Neuron as an Output.
# Also he Sigmoid activation function gives both the Predictions and the probability of the Prediction hence for the 
# for Output layer with Binary Outputs we always use the Sigmoid Function.
# and for Non-Binary Outputs we use 'softmax' activation function.

## Part 3 - Training the ANN

### Step 1 - Compiling the ANN

In [14]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
# 'adam' can perform Stochastic Gradient Descent hence it's the best.
# 'loss' is the 'loss Function' - for binary outputs use only 'binary_crossentropy'.
# for non boinary we use 'categorical_crossentropy'.


### Step2 - Training the ANN on the Training set

In [16]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 500)

Epoch 1/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3285 - accuracy: 0.8654
Epoch 2/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3290 - accuracy: 0.8669
Epoch 3/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8662
Epoch 4/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3289 - accuracy: 0.8660
Epoch 5/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8654
Epoch 6/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3288 - accuracy: 0.8670
Epoch 7/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8674
Epoch 8/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3282 - accuracy: 0.8669
Epoch 9/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3287 - accuracy: 0.8666
Epoch 10/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3286 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.3268 - accuracy: 0.8658
Epoch 82/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3270 - accuracy: 0.8676
Epoch 83/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3270 - accuracy: 0.8666
Epoch 84/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3264 - accuracy: 0.8668
Epoch 85/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3268 - accuracy: 0.8646
Epoch 86/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8670
Epoch 87/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3267 - accuracy: 0.8669
Epoch 88/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3262 - accuracy: 0.8666
Epoch 89/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3264 - accuracy: 0.8676
Epoch 90/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 

250/250 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8681
Epoch 161/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8683
Epoch 162/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3252 - accuracy: 0.8664
Epoch 163/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3261 - accuracy: 0.8673
Epoch 164/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8661
Epoch 165/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8662
Epoch 166/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8661
Epoch 167/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8668
Epoch 168/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3259 - accuracy: 0.8673
Epoch 169/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3259 - a

250/250 [==============================] - 0s 1ms/step - loss: 0.3256 - accuracy: 0.8670
Epoch 240/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8659: 0s - loss: 0.3206 - accura
Epoch 241/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3255 - accuracy: 0.8685
Epoch 242/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8679
Epoch 243/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3255 - accuracy: 0.8664
Epoch 244/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3257 - accuracy: 0.8662
Epoch 245/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8685
Epoch 246/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8661
Epoch 247/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3256 - accuracy: 0.8676
Epoch 248/500
250/250 [==============================] - 0s

250/250 [==============================] - 0s 1ms/step - loss: 0.3244 - accuracy: 0.8670
Epoch 319/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3239 - accuracy: 0.8674
Epoch 320/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3241 - accuracy: 0.8694
Epoch 321/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3243 - accuracy: 0.8679
Epoch 322/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3242 - accuracy: 0.8673
Epoch 323/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3240 - accuracy: 0.8686
Epoch 324/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8674
Epoch 325/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3244 - accuracy: 0.8679
Epoch 326/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3245 - accuracy: 0.8671
Epoch 327/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3241 - a

250/250 [==============================] - 0s 1ms/step - loss: 0.3235 - accuracy: 0.8684
Epoch 398/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3236 - accuracy: 0.8677
Epoch 399/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3238 - accuracy: 0.8680
Epoch 400/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3238 - accuracy: 0.8674
Epoch 401/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3235 - accuracy: 0.8673
Epoch 402/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3237 - accuracy: 0.8687
Epoch 403/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3242 - accuracy: 0.8681
Epoch 404/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3235 - accuracy: 0.8691
Epoch 405/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3238 - accuracy: 0.8683
Epoch 406/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3237 - a

250/250 [==============================] - 1s 2ms/step - loss: 0.3233 - accuracy: 0.8664
Epoch 477/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3240 - accuracy: 0.8671
Epoch 478/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3231 - accuracy: 0.8683
Epoch 479/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3237 - accuracy: 0.8686
Epoch 480/500
250/250 [==============================] - 1s 2ms/step - loss: 0.3237 - accuracy: 0.8685
Epoch 481/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3240 - accuracy: 0.8677
Epoch 482/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3232 - accuracy: 0.8679
Epoch 483/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3234 - accuracy: 0.8673
Epoch 484/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3238 - accuracy: 0.8674
Epoch 485/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3234 - a

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [20]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

array([[0.02418515]], dtype=float32)

This the Probability of the Customer Leaving the bank, and If the probability is more than 0.5 then He is more likely to leave the bank hence If we want just than as Ans we will check if it's Morethan 0.5 or not

In [17]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


### Predicting the Test set results

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1513   82]
 [ 194  211]]


0.862