# Importing Libraries

In [4]:
# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing Dataset

In [6]:
dataset = pd.read_csv("Data.csv")
print("Dataset:\n",dataset.head())

Dataset:
    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes


## Now we need to separate the Features and Label

In [9]:
x = dataset.iloc[:, :-1].values # iloc - Locate Indices
y = dataset.iloc[:, -1].values
print("\nx:\n", x[:5])
print("\ny:\n", y[:5])


x:
 [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]]

y:
 ['No' 'Yes' 'No' 'No' 'Yes']


# Checking for missing values

In [10]:
print(dataset.isnull().sum())

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


# If there are missing values perform this cell

In [13]:
# If there are missing values perform this

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:, 1:3])
x[: ,[1,2]]  = imputer.transform(x[:, [1,2]])
print("x:\n",x[:5])

x:
 [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]]


# If there is categorical feature in the Dataset use - OneHotEncoder

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(drop="first"),[0])], 
                       remainder="passthrough")
x = ct.fit_transform(x)

# our ML Model expects training data to be in np.array formt
x = np.array(x)
print("OneHotEncoded x\n", x[:5])

OneHotEncoded x
 [[0.0 0.0 44.0 72000.0]
 [0.0 1.0 27.0 48000.0]
 [1.0 0.0 30.0 54000.0]
 [0.0 1.0 38.0 61000.0]
 [1.0 0.0 40.0 63777.77777777778]]


# If the feature is Qualitative or binary use - LabelEncoder

In [15]:

# If the feature is Qualitative or binary use - LabelEncoder

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print("Label Encoded y:\n", y[:5])



Label Encoded y:
 [0 1 0 0 1]


# Train Test Splitting

In [16]:
# Train Test Splitting
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

# Feature Scaling

In [17]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 2:] = sc.fit_transform(x_train[:, 2:])
x_test[:, 2:] = sc.transform(x_test[:, 2:])
print("x_train:\n",x_train[:5])

x_train:
 [[0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 1.0 -1.9018011447007988 -1.420463615551582]]
