# Notes_Random_Forest

### Random Forest is a Bagging Algorithm which uses Decision Trees as its base model.

### What is Bagging?

Bagging is an ensembled technique in which 
1. We Sample the data **with replacement**,  (The data sampling is called Boot-strap.)

2. We feed that data to Multiple base models.

3. And finally we aggregate the predictions from these models.
    1. For Classification we go for voting
    2. for Regression we go for Mean or Median of the results.
    
### What are the Advantages of Bagging over Single Model?
1. Bagging significantly decreases the variance without increasing bias.

2. Bagging is Stable in case of outliers, Because the outliers gets randomly separated in the sampled datasets.

3. The Bagging Method works well bcz of Diversity in the Training data, which is caused by the Boot-strap sampling.

4. Bagging can save Computational time and resources by traing the model on reltively small subsets of data and still increase the accuracy.

### What are the Disadvantage of a Bagging Model? 

The main disadvantage of Bagging is that it improves the accuracy of the model on the expense of interpretability

### What is Out-Of-Bag Evaluation?

In Bagging the sampled datasets contain only a fraction of the main data. There are always some data points which never gets used for training the model(these instances are called out of bag instances) and hence can be used as the validation dataset. Hence we do not need a separate validation dataset.

## Python implementation of Bagging.

In [2]:
from sklearn.datasets import load_breast_cancer
dataset = load_breast_cancer()

# Separating Features and Columns
X = dataset.data
y = dataset.target

In [3]:
# Splitting the Training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Training an Individual Algorithm without Bagging.

In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
print("KNN Score: ",knn.score(X_test, y_test))
print("\nConfusion Mtrix for KNN:\n", confusion_matrix(y_test, y_pred))

KNN Score:  0.9385964912280702

Confusion Mtrix for KNN:
 [[44  3]
 [ 4 63]]


## Now let's use bagging over KNN 

In [7]:
from sklearn.ensemble import BaggingClassifier
knn2 = KNeighborsClassifier(n_neighbors=5)
bag_knn = BaggingClassifier(base_estimator=knn2,
                            n_estimators=10,
                            max_samples=0.5,
                            oob_score=True,
                            random_state=3 )
bag_knn.fit(X_train, y_train)
y_pred2 = bag_knn.predict(X_test)
print("Bagging Score: ", bag_knn.score(X_test, y_test))
print("\nConfusioin Matrix:\n", confusion_matrix(y_test, y_pred2))

Bagging Score:  0.9649122807017544

Confusioin Matrix:
 [[44  3]
 [ 1 66]]


### Great the Accuracy Improved by 3%.

### Now Let's Talk about Random Forest

## What is Random Forest?

Decision tree has low bias and high variance hence Decision Trees tends to overfit the dataset. Hence we can use the Decision trees as base model in Bagging so that the variance gets reduced.

Or Instead of using bagging model with decision trees we can use **Random Forest**.

### What's the advantage of Random Forest over Bagging with decision trees?
The advantage of Random forests over bagging models is that the Random Forests makes a tweak in the working algorithm of bagging model to decrease the correlation in trees. The idea is to introduce more randomness while creating trees which will help in reducing correlation.

# Explain the Random Forest Algorithm.

1. just like Bagging Algorithm we use boot-strap for Sampling the dataset.
2. Then we train our tree models on this data subsets and we allow the trees to grow to depths.
    
    Now The main difference between the Bagging with Decision Trees and Random Forest Algorithm is How the Trees are formed in Random Forest.
    
    In Bagging we allow all the Features/ Columns/ Predictors to be used for Splitting the node.
    But in Random Forest each time a split is to happen a random sample of 'm' predictors /features are selected out of total predictors for sampling, i.e. Column sampling with replacement is introduced at the time of Splitting.
    
### Why The Column Sampling with replacement is done at the time of tree splitting?
    
Suppose in those total ‘p’ predictors, 1 predictor is very strong. Now in each sample this predictor will remain the strongest. So, whenever trees will be built for these sampled data, this predictor will be chosen by all the trees for splitting and thus will result in similar kind of tree formation for each bootstrap model. This introduces correaltion in the dataset and averaging correalted dataset results do not lead low variance. That’s why in random forest the choice for selecting node for split is limited and it introduces randomness in the formation of the trees as well.
    
    Most of the predictors are not allowed to be considered for split.
    Generally, value of ‘m’ is taken as m ≈ √p , where ‘p’ is the number of predictors in the sample.

    When m=p , the random forest model becomes bagging model.   
              
    *This method is also referred as “Feature Sampling”
 

### What are the Advantages of Random Forest?
1. It can be used for both Classification and Regression.
2. Since the base model is a Decision Tree, missing values gets handled.
3. Outliers doesn't affect the model much.
4. As the variance is very low the results are very accurate.


### What are the Disadvantages of Random Forest?
1. High coimputational time.
2. Results are very hard to interpret.

# Let's see the Python Implementation of Random Forest.

Here we are classifying the wine depending on it's quality.

In [8]:
import pandas as pd 
dataset = pd.read_csv("winequality_red-Copy1.csv")
dataset.head()

C:\Users\akash\.conda\envs\General\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [9]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### First let's check the results of Individual Decisipon Tree Model.

In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
dt_classifier = DecisionTreeClassifier()

dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_test)

print("Accuracy of a single Decision Tree model:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy of a single Decision Tree model: 0.653125

Confusion Matrix:
 [[ 0  0  0  2  0  0]
 [ 1  2  4  4  0  0]
 [ 2  4 96 31  2  0]
 [ 1  3 31 94 12  1]
 [ 0  0  1  5 17  4]
 [ 0  0  0  2  1  0]]


## Now let's try the Random Forest

In [14]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(random_state=0)

rf_classifier.fit(X_train, y_train)

y_pred2 = rf_classifier.predict(X_test)

print("Accuracy of Random Forest:", accuracy_score(y_test, y_pred2))

print("\nConfusion matrix for Random Forest:\n", confusion_matrix(y_test, y_pred))

Accuracy of Random Forest: 0.7125

Confusion matrix for Random Forest:
 [[ 0  0  0  2  0  0]
 [ 1  2  4  4  0  0]
 [ 2  4 96 31  2  0]
 [ 1  3 31 94 12  1]
 [ 0  0  1  5 17  4]
 [ 0  0  0  2  1  0]]


### Our accuracy Improved by 6%.